### ISSUE TITLE
[Bug] tilda home reference issue

### ISSUE THREAD

**Issue by erpadmin** [JacobCallahan/Hussh#21]
**Hussh Version**
The version of Hussh you have installed.

**Describe the bug**
tilda home reference doesn't work for me

```
from hussh import Connection

conn = Connection(host="jumpops", username="user", private_key="~/.ssh/id_ecdsa")
result = conn.execute("ls")
print(result.stdout)
```
$ python test.py 
Traceback (most recent call last):
  File "/home/user/test.py", line 3, in <module>
    conn = Connection(host="jumpops", username="user", private_key="~/.ssh/id_ecdsa")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
connection.AuthenticationError: [Session(-16)] Unable to extract public key from private key file: Unable to open private key file

**To Reproduce**
specify private_key="~/.ssh/id_ecdsa" rather than "/home/user/.ssh/id_ecdsa (which works)

**Expected behavior**
either it work or the readme updated accordingly

**Comment by JacobCallahan** [comment]
To verify, does the fully resolved path work for you?

**Comment by erpadmin** [comment]
yes.  this isn't a huge deal, and it is not the first time a Python app doesn't actually expand Tilda.  I'm on rocky using bash, not sure if it has influence on it.

**Comment by JacobCallahan** [comment]
@erpadmin the latest release has this in.
