### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by thewchan** [JacobCallahan/Hussh#23]
Hi! I'm hoping to add this package onto Conda Forge, and that would require a license file to be included in the source distribution. Can that be added?

**Comment by thewchan** [comment]
Thanks @JacobCallahan; they generally prefer license listed in https://spdx.org/licenses/, but for example the MIT license is very short and no frills and very permissible. See: https://spdx.org/licenses/MIT.html

**Comment by JacobCallahan** [comment]
I've used that one in the past when I wanted a more formal license. I'm generally not a fan of how restrictive and rigid many licenses are, but I'll likely adopt MIT's for now.

**Comment by thewchan** [comment]
Thanks @JacobCallahan; for what it's worth https://spdx.org/licenses/Apache-2.0.html is another very popular one that's permissive. It's quite a bit meatier so you can check that one out.
