### ISSUE TITLE
[RFE] Add option to execute() to set stdin

### ISSUE THREAD

**Issue by braincore** [JacobCallahan/Hussh#25]
**Is your feature request related to a problem? Please describe.**

A way to write to the stdin of an executed command.

**Describe the solution you'd like**

```
conn.execute(cmd, timout, stdin)
```

**Describe alternatives you've considered**

Rewrite the exec command to use an echo & pipe.

**Comment by JacobCallahan** [comment]
Can you elaborate on what specifically you're trying to do? All executes should be writing to stdin. For example:
```python
In [1]: from hussh import Connection

In [2]: conn = Connection("my.test.host.com", password="dog8code")

In [3]: conn.execute("whoami")
Out[3]: 
SSHResult(stdout=root
, stderr=, status=0)

In [4]: conn.execute('echo "test" | grep es')
Out[4]: 
SSHResult(stdout=test
, stderr=, status=0)
```

**Comment by braincore** [comment]
Have a file-like object method for injecting `stdin`. In `ssh2-python`, the channel object lets you `chan.write(stdin)`.

`echo "test"` is certainly doable but is cumbersome for large stdin especially if it requires escaping.

**Comment by JacobCallahan** [comment]
Can you give me a more concrete example of how you used this in ssh2-python and/or how you'd expect to do that with Hussh?

Right now it doesn't sound like something that should be rolled into execute, but I'm not yet sure.

**Comment by braincore** [comment]
I reviewed some internal use cases and you're right. It's rarely used, and when it is, it's for one of two reasons:

1. Bespoke programs that only take stdin without any command-line flag alternative.
2. Programs that don't have a `-y` mode (auto-accept / do-not-prompt) and require stdin input to make progress.

Leaving these unsupported is fine.

**Comment by JacobCallahan** [comment]
For those, `Channel.shell()` might be a good option, since it allows you to send more "interactive" style input.

https://github.com/JacobCallahan/Hussh?tab=readme-ov-file#interactive-shell
